# Generated by Django 5.2.5 on 2025-11-25 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='tmdb_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
